[workspace]
resolver = "2"
members = [
    "crates/app-common",
    "crates/core-capture",
    "crates/core-codec",
    "crates/core-input",
    "crates/core-net",
    "crates/open-remote-cli",
    "app-ui/src-tauri",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

